# Структурно програмирање
Аудиториски вежби 2
{docdate}

include::parts/attributes.adoc[]

:source_dir: ../../src/av2

== Структура на програма

Потсетување: изворниот код на програмскиот јазик
*C* е организиран во функции

[.Програма во C]
[source,c]
----
int main() {
  deklaracija na promenlivi;
  programski_naredbi;
}
----

== Функции во C

- `main`
- Функциите може да примаат влезни аргументи во делот ()
- Типот на резултатот кој го враќа функцијата стои пред
името на функцијата (`int` – функцијата враќа цел број)
- Телото на функцијата започнува со `{`, а завршува со `}`
- Сите наредби се одделуваат меѓусебно со `;`

== Употреба на коментари

За дополнително до објаснување или документирање на изворниот код се
користат коментари. Постојат два вида коментари:

- коментари во еден ред
----
// komentar vo eden red
----

- коментари во повеќе редови
----
/*
komentar vo
povekje redovi
*/
----

=== Основна програма во C

.Пример 1
[source,c]
----
include::{source_dir}/ex21.c[]
----

- `#include` - директива за вклучување на надворешни библиотеки
- `stdio.h` - библиотека за работа со стандардни влезно/излезни текови
(тастатура, екран)
- `printf` - функција за печатње на стандарден излез

=== Основна програма во C++

.Пример 1
[source,cpp]
----
include::{source_dir}/ex21.cpp[]
----

- `#include` - директива за вклучување на надворешни библиотеки
- `stdio.h` - библиотека за работа со стандардни влезно/излезни текови
(тастатура, екран)
- `printf` - функција за печатње на стандарден излез

=== Програма за собирање два броја

.Решение 
[source,c]
----
include::{source_dir}/ex22.c[]
----

== Именувани константи

Именуваните константи се креираат со користење на клучниот збор `const`

.Пример
[source,c]
[source,c]
----
include::{source_dir}/ex23.c[]
----

Именуваните константи може да се креираат и со користење на 
претпроцесорот и за нив по правило се користат големи букви

Користење на `#define`

`#define tekst_za_baranje tekst_za_zamena`

== Аритметички оператори

Се применуваат на броеви (цели или децимални)

[options="header"]
|===
| Оператор | Операција
| +        | Собирање
| -        | Одземање
| *        | Множење
| /        | Делење
| %        | Делење по модул (остаток при делењето)
|===

== Ознаки за форамтот на печатењето

[options="header"]
|===
| Ознака | Објаснување
| *`%d`*      | за цели броеви
| `%i`        | за цели броеви
| `%c`        | за знаци
| `%s`        | за низа од знаци (стринг)
|===

=== Пример на користење на функцијата `printf`

Да се отпечати на екран во следниов редослед:
----
Prva recenica.
Vtora recenica.
Treta recenica.
----

.Пример 3
[source,c]
----
include::{source_dir}/ex25.c[]
----

.Пример 3 (C++)
[source,c]
----
include::{source_dir}/ex25.cpp[]
----

== Задачи

=== Задача 1

Да се напише програма која ќе ја пресметува вредноста на математичкиот 
израз: `x = 3/2 + (5 – 46*5/12)`

.Решение 1
[source,c]
----
include::{source_dir}/p21.c[]
----

=== Задача 2

Да се напише програма која за зададена вредност на х 
(при декларација на променливата) ќе го пресмета и отпечати на екран х^2^.

.Решение 2
[source,c]
----
include::{source_dir}/p22.c[]
----

.Решение 2 (C++)
[source,cpp]
----
include::{source_dir}/p22.cpp[]
----

=== Задача 3

Да се напише програма која за дадени страни на еден разностран триаголник 
ќе ги отпечати на екран периметарот и квадратот од 
плоштината (нека се работи со `a = 5`, `b = 7.5`, `c = 10.2`).

.Решение 3
[source,c]
----
include::{source_dir}/p23.c[]
----

.Решение 3 (C++)
[source,cpp]
----
include::{source_dir}/p23.cpp[]
----

=== Задача 4

Да се напише програма за пресметување на аритметичката 
средина на броевите 3, 5 и 12.

.Решение 4
[source,c]
----
include::{source_dir}/p24.c[]
----

=== Задача 5

Да се напише програма која ќе ги отпечати на екран 
остатоците при делењето на бројот 19 со 2, 3, 5 и 8.

.Решение 5
[source,c]
----
include::{source_dir}/p25.c[]
----

=== Задача 6

Да се напише програма за пресметување и печатење на плоштината и 
периметарот на круг. Радиусот на кругот се чита од стандарден влез 
(тастатура) како децимален број.

.Решение 6
[source,c]
----
include::{source_dir}/p26.c[]
----

=== Задача 7

Да се напише програма која од СВ ќе прочита два цели 
броеви и ќе ја испечати на компјутерскиот екран нивната сума, 
разлика, производ и остатокот при делењето.

.Решение 7
[source,c]
----
include::{source_dir}/p27.c[]
----

=== Задача 8

Да се напише програма која чита големa буквa од стандарден влез и ја печати
истaтa како малa буквa.

TIP: Секој знак се претставува со ASCII број.

.пример
----
A = 65, a = 97
----

.Решение 8
[source,c]
----
include::{source_dir}/p28.c[]
----

include::parts/footer.adoc[]

