# Структурно програмирање
Аудиториски вежби 3
{docdate}

include::parts/attributes.adoc[]

:source_dir: ../../src/av3

== Потсетување од предавања
* Оператори
** Аритметички
** Релациски
** Логички
* Промена на вид на вредност – *cast* операција

=== Релациски оператори
Се применуваат над било кои споредливи типови на податоци, а резултатот е цел број 0 (неточно) или 1 (точно).

[options="header",cols="^,3"]
|===
| Оператор | Значење
| `<`      | Помало
| `\<=`    | Помало или еднакво
| `>`      | Поголемо
| `>=`     | Поголемо или еднакво
| `==`     | Еднаквост
| `!=`     | Не еднаквост (различно)
|===

=== Логички оператори
Се користат најчесто во комбинација со релационите оператори за формирање на сложени логички изрази, кои повторно враќаат резултат 0 или 1

[options="header",cols="^,3"]
|===
| Оператор | Операција
| `&&`     | Логичко *И* (AND)
| `\|\|`   | Логичко *ИЛИ* (OR)
| `!`      | Негација
|===
Пример:
[source,c]
----
int a = 5 && 0; // a = 0;
a = 2 && 5;     // a = 1;
a = 0 || 5;     // a = 1;
a = !0;         // a = 1;
a = !5;         // a = 0;
----

=== Дополнителни оператори

* Оператор за доделување =
* Оператори за инкрементирање и декрементирање (++, --)
** `++` инкрементирање (зголемување на вредноста на операндот за 1)
** `--` декрементирање (намалување на вредноста на операндот за 1)
* Користење на операторите + и – на унарен начин
[source,c]
----
X = + Y;
X = - Y;
----

* Двојни оператори
** Комбинација од оператор за доделување и друг оператор (+=, -=, *=, /=, %=)

=== Оператор за доделување =
* Сите изрази имаат вредност, дури и оние кои содржат =
* Вредноста на таков израз е вредноста на изразот кој се наоѓа на десна страна
* Затоа е можно и доделување од следниот облик:
[source,c]
----
 x = (y = 10) * (z = 5);
 x = y = z = 20;
----

=== Оператори за инкрементирање и декрементирање 

* Оператор за инкрементирање ++ (зголемување на вредноста на операндот за 1)
* Оператор за декрементирање --(намалување на вредноста на операндот за 1)
* Можат да бидат зададени во префикс или постфикс нотација:
** префикс - вредноста на променливата се зголемува пред да се пресмета изразот во која таа учествува
[source,c]
----
	a = ++b;
----
	
** постфикс - вредноста на променливата се зголемува откако ќе се пресмета изразот
[source,c]
----
	a = b++;
----

=== Двојни оператори
 
* Оператор +=
[source,c]
----
a += 5; // a = a + 5;
a += b * c; // a = a + b * c;
----
* Оператор -=
[source,c]
----
a -= 3; // a = a – 3;
----
* Оператор *=
[source,c]
----
a *= 3; // a = a * 3;
----
* Оператор /=
[source,c]
----
a /= 3; // a = a / 3;
----
* Оператор %=
[source,c]
----
a %= 3; // a = a % 3;
----

== Пример 1
Работа со променливи и доделување вредности

[source,c]
----
include::{source_dir}/p3_1.c[]
----

.Решение 2 (C++)
[source,cpp]
----
include::{source_dir}/p22.cpp[]
----

=== Задача 3

Да се напише програма која за дадени страни на еден разностран триаголник 
ќе ги отпечати на екран периметарот и квадратот од 
плоштината (нека се работи со `a = 5`, `b = 7.5`, `c = 10.2`).

.Решение 3
[source,c]
----
include::{source_dir}/p23.c[]
----

.Решение 3 (C++)
[source,cpp]
----
include::{source_dir}/p23.cpp[]
----

=== Задача 4

Да се напише програма за пресметување на аритметичката 
средина на броевите 3, 5 и 12.

.Решение 4
[source,c]
----
include::{source_dir}/p24.c[]
----

=== Задача 5

Да се напише програма која ќе ги отпечати на екран 
остатоците при делењето на бројот 19 со 2, 3, 5 и 8.

.Решение 5
[source,c]
----
include::{source_dir}/p25.c[]
----

=== Задача 6

Да се напише програма за пресметување и печатење на плоштината и 
периметарот на круг. Радиусот на кругот се чита од стандарден влез 
(тастатура) како децимален број.

.Решение 6
[source,c]
----
include::{source_dir}/p26.c[]
----

=== Задача 7

Да се напише програма која од СВ ќе прочита два цели 
броеви и ќе ја испечати на компјутерскиот екран нивната сума, 
разлика, производ и остатокот при делењето.

.Решение 7
[source,c]
----
include::{source_dir}/p27.c[]
----

=== Задача 8

Да се напише програма која чита големa буквa од стандарден влез и ја печати
истaтa како малa буквa.

TIP: Секој знак се претставува со ASCII број.

.пример
----
A = 65, a = 97
----

.Решение 8
[source,c]
----
include::{source_dir}/p28.c[]
----

include::parts/footer.adoc[]

