# Структурно програмирање
Аудиториски вежби 2
{docdate}

include::parts/attributes.adoc[]

:source_dir: ../../src/av2

== Структура на програма

=== Задача 2

Да се напише програма која за зададена вредност на х 
(при декларација на променливата) ќе го пресмета и отпечати на екран х^2^.

.Решение 2
[source,c]
----
include::{source_dir}/p22.c[]
----

.Решение 2 (C++)
[source,cpp]
----
include::{source_dir}/p22.cpp[]
----

=== Задача 3

Да се напише програма која за дадени страни на еден разностран триаголник 
ќе ги отпечати на екран периметарот и квадратот од 
плоштината (нека се работи со `a = 5`, `b = 7.5`, `c = 10.2`).

.Решение 3
[source,c]
----
include::{source_dir}/p23.c[]
----

.Решение 3 (C++)
[source,cpp]
----
include::{source_dir}/p23.cpp[]
----

=== Задача 4

Да се напише програма за пресметување на аритметичката 
средина на броевите 3, 5 и 12.

.Решение 4
[source,c]
----
include::{source_dir}/p24.c[]
----

=== Задача 5

Да се напише програма која ќе ги отпечати на екран 
остатоците при делењето на бројот 19 со 2, 3, 5 и 8.

.Решение 5
[source,c]
----
include::{source_dir}/p25.c[]
----

=== Задача 6

Да се напише програма за пресметување и печатење на плоштината и 
периметарот на круг. Радиусот на кругот се чита од стандарден влез 
(тастатура) како децимален број.

.Решение 6
[source,c]
----
include::{source_dir}/p26.c[]
----

=== Задача 7

Да се напише програма која од СВ ќе прочита два цели 
броеви и ќе ја испечати на компјутерскиот екран нивната сума, 
разлика, производ и остатокот при делењето.

.Решение 7
[source,c]
----
include::{source_dir}/p27.c[]
----

=== Задача 8

Да се напише програма која чита големa буквa од стандарден влез и ја печати
истaтa како малa буквa.

TIP: Секој знак се претставува со ASCII број.

.пример
----
A = 65, a = 97
----

.Решение 8
[source,c]
----
include::{source_dir}/p28.c[]
----

include::parts/footer.adoc[]

