# Структурно програмирање
Аудиториски вежби 7
include::parts/attributes.adoc[]

:source_dir: ../../src/av7

== Функции

=== Потсетување од предавања

==== Дефиниција на функција во C

[source,c]
----
tip ime(lista_na_formalni_argumenti) {
  telo_na_funkcijata
}
----

- tip - типот на вредноста која ја враќа функцијата
- ime - името на функцијата
- lista_na_formalni_argumenti - листата со формални аргументи ги содржи аргументите заедно со нивните типови, разделени со запирка
- telo_na_funkcijata - телото на функцијата ги содржи истите елементи како и самата `main()` функција

==== Повик на функција

[source,c]
----
ime(lista_na_argumenti);
----

- ime - името на веќе дефинираната функција
- lista_na_argumenti - листата на аргументи е со вистински аргументи кои што ако се повеќе ако се одделуваат со запирка

==== Пример на кориснички дефинирана функција

Да се напише програма во која со посебна функција се пресметува куб stem:[n^3] за вчитан природен број n.

.Пример `ex7_1.c`
[source,c]
----
include::{source_dir}/ex7_1.c[]
----

=== Функции од математичката библиотека `math.h`

- Во C постои стандардна математичка библиотека `math.h` која што содржи многу готови математички функции.
- За да се употребува, треба претходно да се вклучи со:
`#include <math.h>`
- Сите функции од стандардната библиотека `math.h` примаат аргументи од тип `double` и враќаат вредности од истиот тип.

=== Најчесто користени математички функции

[options="header",cols="^,^4"]
|===
| Функција     | Објаснување
| `sqrt(x)`    | квадратен корен од `x`  
| `exp(x)`     | експоненцијална функција  stem:[е^х]         
| `log(x)`     | природен логаритам од х (со основа е)
| `log10(x)`   | логаритам од х со основа 10
| `fabs(x)`    | апсолутна вредност од х
| `ceil(x)`    | заокружува х на најмалиот цел број не помал од х
| `floor(x)`   | заокружува х на најголемиот цел број не поголем од х
| `pow(x, y)`  | x на степен y
| `fmod(x, y)` | остаток од х/у како реален број
| `sin(x)`     | синус од х (во радијани)
| `cos(x)`     | косинус од х (во радијани)
| `tan(x)`     | тангенс од х (во радијани)
|===

==== Пример на користење на функција од `math.h`

Да се напише програма во која со посебна функција се пресметува куб stem:[n^3] за вчитан природен број n.

.Пример `ex7_2.c`
[source,c]
----
include::{source_dir}/ex7_2.c[]
----

=== Задача 1

Да се напишат соодветни функции за пресметување на дијаметар, периметар и плоштина на круг чиј што радиус се предава како аргумент. 
Потоа да се напише и програма во која за внесен (од тастатура) радиус ќе се повикаат овие функции за да се пресметаат дијаметарот, периметарот и плоштината на соодветниот круг.

.Решение `p7_4.c`
[source,c]
----
include::{source_dir}/p7_4.c[]
----

=== Задача 2

Да се напише програма која што ќе ги отпечати сите четирицифрени природни броеви кои се деливи со збирот на двата броја составени од првите две цифри и од последните две цифри на четирицифрениот број. 
На крајот треба да отпечати и колку вакви броеви се пронајдени.

Пример:
----
3417 е делив со 34 + 17
5265 е делив со 52 + 65
6578 е делив со 65 + 78
----

.Решение `p7_5.c`
[source,c]
----
include::{source_dir}/p7_5.c[]
----

=== Задача 3

Да се напише програма која за даден природен број ја пресметува разликата помеѓу најблискиот поголем од него прост број и самиот тој број.

Пример:
Ако се внесе 573, програмата треба да испечати 577 – 573 = 4

.Решение `p7_6.c`
[source,c]
----
include::{source_dir}/p7_6.c[]
----

=== Задача 4

Да се напише програма што ќе ги отпечати сите прости броеви помали од 10000 чиј што збир на цифри е исто така прост број. 
На крајот да се отпечати колку вакви броеви се пронајдени.

.Решение `p7_7.c`
[source,c]
----
include::{source_dir}/p7_7.c[]
----

=== Задача 5

Да се напише програма што ќе ги отпечати сите парови прости броеви помали од 1000 што се разликуваат меѓу себе за 2. 
На крај да се отпечати и нивниот број.

.Решение `p7_8.c`
[source,c]
----
include::{source_dir}/p7_8.c[]
----

=== Задача 6

Да се пресмета збирот:

1! + (1 + 2)! + (1 + 2 + 3)! + ... + (1 + 2 + ... + n)!

TIP: Користете функција за пресметување на збирот на првите k природни броеви
Користете функција за пресметување факториел на еден природен број k

.Решение `p7_9.c`
[source,c]
----
include::{source_dir}/p7_9.c[]
----


include::parts/footer.adoc[]

link:{sources_zip}/sp_av7_src.zip[Source code ZIP]
