# Структурно програмирање
Аудиториски вежби 6
include::parts/attributes.adoc[]

:source_dir: ../../src/av6
== Низи `[]`

=== Декларација на низа

[source,c]
----
type variable_name[SIZE];

int a[10];
float x[99];
char c[5];
----

=== Пристап на елемент од низа

[source,c]
----
array[element_index];

int a[10];
a[0] = 1; // доделување вредност 1 на првиот елемент
printf("%d", a[9]); // печатење на вредноста на последниот елемент
----

== Задачи

=== Задача 1

Да се напише програма која за две низи кои се внесуваат од тастатура ќе провери дали се еднакви или не. 
На екран да се испачати резултатот од споредбата.
Максимална големина на низите е 100.

.Решение `p6_1.c`
[source,c]
----
include::{source_dir}/p6_1.c[]
----

=== Задача 2

Да се напише програма која за низа чии елементи се внесуваат од тестатура, ќе го пресмета збирот на парните елементи, збирот на непарните елементи, како и односот помеѓу бројот на парни и непарни елементи. 
Резултатот да се испечати на екран.

.Пример
За низата:
`3 2 7 6 2 5 1`
На екран ќе се испечати:
----
Suma parni: 8
Suma neparni: 16
Odnos: 0.75
----

.Решение `p6_2.c`
[source,c]
----
include::{source_dir}/p6_2.c[]
----

=== Задача 3

Да се напише програма која ќе го пресмета скаларниот производ на два вектори со по `n` координати. 
Бројот на координати `n`, како и координатите на векторите се внесуваат од стандарден влез. 
Резултатот да се испечати на екран. 

.Решение `p6_3.c`
[source,c]
----
include::{source_dir}/p6_3.c[]
----

=== Задача 4

Да се напише програма која ќе провери дали дадена низа од `n` елементи која се чита од стандарден влез е _строго растечка_, _строго опаѓачка_ или ниту строго растечка ниту строго опаѓачка.
Резултатот да се испечати на екран.

.Решение `p6_4.c`
[source,c]
----
include::{source_dir}/p6_4.c[]
----

=== Задача 5

Да се напише програма за ротирање на елементите на една низа за едно место во десно. На крај, да се испечати на екран ротираната низа. Елементите од низата се читаат од стандарден влез.

.Решение `p6_5.c`
[source,c]
----
include::{source_dir}/p6_5.c[]
----

=== Задача 6

Да се напише програма за ротирање на елементите на една низа за m местa во десно. На крај, да се испечати на екран ротираната низа. Елементите од низата и бројот на ротирања се читаат од стандарден влез.

.Решение `p6_6.c`
[source,c]
----
include::{source_dir}/p6_6.c[]
----

=== Задача 7

Да се напише програма која што ќе ги избрише дупликатите од една низа. 
На крај, да се испечати на екран новодобиената низа. 
Елементите од низата се читаат од стандарден влез.

.Решение `p6_7.c`
[source,c]
----
include::{source_dir}/p6_7.c[]
----

== Матрици (дво димензионални низи)

=== Задача 1

Да се напише програма која за матрица внесена од тастатура ќе ја пресмета разликата на збирот на елементите на непарните колони и збирот на елементите на парните редици. 
Матрицата не мора да биде квадратна.

.Решение `p7_1.c`
[source,c]
----
include::{source_dir}/p6_8.c[]
----

=== Задача 2

Да се напише програма која за матрица внесена од тастатура ќе ги замени елементите од главната дијагонала со разликата од максималниот и минималниот елемент во матрицата. 
Резултантната матрица да се испечати на екран.

.Решение `p7_2.c`
[source,c]
----
include::{source_dir}/p6_9.c[]
----

=== Задача 3

Да се напише програма која за квадратна матрица внесена од тастатура ќе испечати на екран дали таа е симетрична во однос на главната дијагонала.

.Решение `p7_3.c`
[source,c]
----
include::{source_dir}/p6_10.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_av6_src.zip[Source code ZIP]
