# Structured programming
Exercises 7
include::parts/attributes_en.adoc[]

:source_dir: ../../src/av7

== Functions

=== Reminder from lectures

==== Defining a function in C

[source,c]
----
return_type name(arguments_list) {
  function_body
}
----

- return_type - type of the return value of the function
- name - name of the function
- arguments_list - list of arguments with names and their types, coma separated
- function_body - the body of the function

==== Calling (using) function

[source,c]
----
name(arguments_values);
----

- name - name of already defined function
- arguments_values - list of values passed as arguments, coma separated

==== Example of user defined function

Write a program with a separate function for computing cube of number stem:[n^3] за вчитан природен број n.

.Example `ex7_1_en.c`
[source,c]
----
include::{source_dir}/ex7_1_en.c[]
----

=== Functions from standard library `math.h`

- C has standard library `math.h` with many useful mathematical functions
- To be used, first it needs to be included:
`#include <math.h>`
- All functions from the standard library `math.h` accepts arguments of type `double` and return values of same type.

=== Most used mathematical functions

[options="header",cols="^,^4"]
|===
| Function     | Explanation
| `sqrt(x)`    | square root of `x`
| `exp(x)`     | exponential function  stem:[е^х]
| `log(x)`     | natural logarithm of x (with base е)
| `log10(x)`   | logarithm of x of base 10
| `fabs(x)`    | absolute value of х
| `ceil(x)`    | rounding х to the smallest integer not smaller than х
| `floor(x)`   | rounding х to the largest integer not larger than х + 1
| `pow(x, y)`  | x to the power of y
| `fmod(x, y)` | residue of х/у as real number
| `sin(x)`     | sine of х (in radians)
| `cos(x)`     | cosine of х (in radians)
| `tan(x)`     | tangent of х (in radians)
|===

==== Example using function from `math.h`

Write a program that will compute cube stem:[n^3] for an integer n.

.Example `ex7_2_en.c`
[source,c]
----
include::{source_dir}/ex7_2_en.c[]
----

=== Problem 1

Write functions to compute diameter, perimeter and area of circle with radius passed as argument to the functions.
Then write a program that for radius read from SI will call the functions to compute the diameter, perimeter and area.

.Solution `p7_4_en.c`
[source,c]
----
include::{source_dir}/p7_4_en.c[]
----

=== Problem 2

Write a program that will print all four digit numbers that are divisible with the sum of the numbers formed from the first two and last two digits of the original number.
Print how many such numbers exist.

Example:
----
3417 is divisible with 34 + 17
5265 is divisible with 52 + 65
6578 is divisible with 65 + 78
----

.Solution `p7_5_en.c`
[source,c]
----
include::{source_dir}/p7_5_en.c[]
----

=== Problem 3

Write a program that for a given natural number will compute the difference between that number and the following prime number.

Example:
For the number 573, the program should print 577 – 573 = 4

.Solution `p7_6_en.c`
[source,c]
----
include::{source_dir}/p7_6_en.c[]
----

=== Problem 4

Write a program that will print all pairs of primes up to 1000 that differentiate between themselves for 2.
At the end print the count.

.Solution `p7_7_en.c`
[source,c]
----
include::{source_dir}/p7_7_en.c[]
----

=== Problem 5

Compute the sum:

1! + (1 + 2)! + (1 + 2 + 3)! + ... + (1 + 2 + ... + n)!

TIP: Use function for computing the sum of the first k natural numbers
Use a function for computing factorial of k

.Solution `p7_9_en.c`
[source,c]
----
include::{source_dir}/p7_9_en.c[]
----


include::parts/footer_en.adoc[]

link:{sources_zip}/sp_av7_src_en.zip[Source code ZIP]
