# Структурно програмирање
Аудиториски вежби 2
v1.0, 20 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/av2

== Структура на програма

Потсетување: изворниот код на програмскиот јазик
*C* е организиран во функции

[.Програма во C]
[source,c]
----
int main() {
  deklaracija na promenlivi;
  programski_naredbi;
}
----

== Функции во C

- `main`
- Функциите може да примаат влезни аргументи во делот ()
- Типот на резултатот кој го враќа функцијата стои пред
името на функцијата (`int` – функцијата враќа цел број)
- Телото на функцијата започнува со `{`, а завршува со `}`
- Сите наредби се одделуваат меѓусебно со `;`

== Употреба на коментари

За дополнително до објаснување или документирање на изворниот код се
користат коментари. Постојат два вида коментари:

- коментари во еден ред
----
// komentar vo eden red
----

- коментари во повеќе редови
----
/*
komentar vo
povekje redovi
*/
----

=== Основна програма во C

.Пример 1
[source,c]
----
include::{source_dir}/ex21.c[]
----

- `#include` - директива за вклучување на надворешни библиотеки
- `stdio.h` - библиотека со функции за работа со стандардни влезно/излезни текови
(тастатура, екран)
- `printf` - функција за печатње на стандарден излез

=== Основна програма во C++

.Пример 1
[source,cpp]
----
include::{source_dir}/ex21.cpp[]
----

- `#include` - директива за вклучување на надворешни библиотеки
- `<iostream>` - библиотека за работа со стандардни влезно/излезни текови
(тастатура, екран)
- `cout` - глобален објект за работа со излезен тек (екран)
- `<<` со оператор за печатење на излезен тек (екран)

=== Програма за собирање два броја

.Пример 2 
[source,c]
----
include::{source_dir}/ex22.c[]
----

== Променливи (variables)

* Променливите се симболички имиња за места во меморијата во кои се чуваат некакви вредности.
* Сите променливи пред да се користат треба да се *декларираат*.
* Со секое ново сместување на вредност во променливата, старата вредност се брише

=== Начин на декларација на променливи

----
тип_на_променлива име_на_променлива = почетна_вредност;
----

.Пример
[source,c]
----
int a = 5;
float x = 2.3;
char c = 'a';
----

=== Типови на променливи во C

[options="header",cols="^,^,^"]
|===
| Цели броеви | Знаковни | Децимални 
| `int`       | `char`   | `float`
| `short`     |          | `double`
| `long`      |          |
|===

=== Дефинирање на имиња на променливи

При именувањето на променливите може да се користат:

* мали букви од `a` до `z`;
* големи букви од `A` до `Z`;
* цифри од `0` до `9` (не смее да започнува со цифра);

TIP: Избирјте имиња на променливи кои јасно го означуваат она што се чува во неа.

WARNING: С ги разликува малите и големите букви!

== Именувани константи

Именуваните константи се креираат со користење на клучниот збор `const`

.Пример 3
[source,c]
----
include::{source_dir}/ex23.c[]
----

Именуваните константи може да се креираат и со користење на 
претпроцесорот и за нив по правило се користат големи букви

Користење на `#define`

`#define tekst_za_baranje tekst_za_zamena`

.Пример 4
[source,c]
----
include::{source_dir}/ex24.c[]
----

== Оператори

=== Аритметички оператори

Се применуваат на броеви (цели или децимални)

[options="header",cols="^,3"]
|===
| Оператор | Операција
| +        | Собирање
| -        | Одземање
| *        | Множење
| /        | Делење
| %        | Делење по модул (остаток при делењето)
|===

=== Релациони оператори

Се применуваат над било кои споредливи типови на податоци, а резултатот е цел број 0 (неточно) или 1 (точно).

[options="header",cols="^,3"]
|===
| Оператор | Значење
| `<`      | Помало
| `\<=`    | Помало или еднакво
| `>`      | Поголемо
| `>=`     | Поголемо или еднакво
| `==`     | Еднаквост
| `!=`     | Не еднаквост (различно)
|===

=== Логички оператори

Се користат најчесто во комбинација со релационите оператори за формирање на сложени логички изрази, кои повторно враќаат резултат 0 или 1

[options="header",cols="^,3"]
|===
| Оператор | Операција
| `&&`     | Логичко *И* (AND)
| `\|\|`   | Логичко *ИЛИ* (OR)
| `!`      | Негација
|===


=== Дополнителни оператори

[options="header",cols="^,3"]
|===
| Оператор | Операција
| `=`      | Доделување (assignment)
| `++`     | Инкреметирање за 1 (increment)
| `--`     | Декрементирање за 1 (decrement)
|===

=== Унарни оператори

Користење на операторите `+` и `–` на унарен начин:

.Менување на знакот на вредноста во променливите `x` и `y`
[source,c]
----
x = +x;
y = -y;
----

==== Двојни оператори

Комбинација од оператор за доделување и друг оператор.

`+=, -=, *=, /=, %=`

.Пример за користење на двојни оператори
[source,c]
----
a += 5; // a = a + 5;
a += b * c; // a = a + b * c;
----

.Пример со променливи и оператори
[source,c]
----
#include <stdio.h>	

int main() {
    int a;
    float p;
    p = 1.0 / 2.0; /* p = 0.5 */
    a = 5 / 2;     /* a = 2   */
    p = 1 / 2 + 1 / 8; /* p = 0; */
    p = 3.5 / 2.8; /* p = 1.25 */
    a = p; /* a = 1 */
    a = a + 1; /* a = 2; */
    return 0;		
}
----

== Печатење на стандарден излез

За печатење на стандарден излез (екран) во C се користи готова функција 
`printf` од бибилиотеката `stdio.h` (**St**andar**d** **I**nput **O**tput) 

`#include <stdio.h>`

Функцијата која се употребува е:

`int printf(kontrolna_niza, lista_na_argumenti)`

_Контролната низа_ содржи било каков текст, ознаки за форматот на печатење 
на аргументите предводени со `%` или специјални знаци кои започнуваат со
`\`.

_Ознаките за форматот на печатење_ се одредуваат според видот на 
променливата чија вредноста треба да се испише.

=== Најчесто користени ознаки за форматот на печатењето

[options="header",cols="^,3"]
|===
| Ознака | Објаснување
| `%d`   | за цели броеви (`int`)
| `%i`   | за цели броеви (`int`)
| `%f`   | за децимални броеви (`float`, `double`)
| `%c`   | за знаци (`char`)
| `%s`   | за низа од знаци (стринг, `char[]`, `char*`)
| `%%`   | за знакот `%`
|===

=== Пример на користење на функцијата `printf`

Да се отпечати на екран во следниов редослед:
----
Prva recenica.
Vtora recenica.
Treta recenica.
----

.Пример 5
[source,c]
----
include::{source_dir}/ex25.c[]
----

.Пример 5 (C++)
[source,c]
----
include::{source_dir}/ex25.cpp[]
----

.Пример 6
[source,c]
----
include::{source_dir}/ex26.c[]
----

== Задачи

=== Задача 1

Да се напише програма која ќе ја пресметува вредноста на математичкиот 
израз: `x = 3/2 + (5 – 46*5/12)`

.Решение 1
[source,c]
----
include::{source_dir}/p21.c[]
----

=== Задача 2

Да се напише програма која за зададена вредност на х 
(при декларација на променливата) ќе го пресмета и отпечати на екран х^2^.

.Решение 2
[source,c]
----
include::{source_dir}/p22.c[]
----

.Решение 2 (C++)
[source,cpp]
----
include::{source_dir}/p22.cpp[]
----

=== Задача 3

Да се напише програма која за дадени страни на еден разностран триаголник 
ќе ги отпечати на екран периметарот и квадратот од 
плоштината (нека се работи со `a = 5`, `b = 7.5`, `c = 10.2`).

.Решение 3
[source,c]
----
include::{source_dir}/p23.c[]
----

.Решение 3 (C++)
[source,cpp]
----
include::{source_dir}/p23.cpp[]
----

=== Задача 4

Да се напише програма за пресметување на аритметичката 
средина на броевите 3, 5 и 12.

.Решение 4
[source,c]
----
include::{source_dir}/p24.c[]
----

=== Задача 5

Да се напише програма која ќе ги отпечати на екран 
остатоците при делењето на бројот 19 со 2, 3, 5 и 8.

.Решение 5
[source,c]
----
include::{source_dir}/p25.c[]
----

=== Задача 6

Да се напише програма за пресметување и печатење на плоштината и 
периметарот на круг. Радиусот на кругот се чита од стандарден влез 
(тастатура) како децимален број.

.Решение 6
[source,c]
----
include::{source_dir}/p26.c[]
----

=== Задача 7

Да се напише програма која од СВ ќе прочита два цели 
броеви и ќе ја испечати на компјутерскиот екран нивната сума, 
разлика, производ и остатокот при делењето.

.Решение 7
[source,c]
----
include::{source_dir}/p27.c[]
----

=== Задача 8

Да се напише програма која чита голема буква од стандарден влез и ја печати
истата како мала буква.

TIP: Секој знак се претставува со ASCII број.

.пример
----
A = 65, a = 97
----

.Решение 8
[source,c]
----
include::{source_dir}/p28.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_av2_src.zip[Source code ZIP]