# Структурно програмирање
Аудиториски вежби 3
include::parts/attributes.adoc[]

:source_dir: ../../src/av3

== Потсетување од предавања
* Оператори
** Аритметички
** Релациски
** Логички
* Промена на вид на вредност – *cast* операција

=== Релациски оператори
Се применуваат над било кои споредливи типови на податоци, а резултатот е цел број 0 (неточно) или 1 (точно).

[options="header",cols="^,3"]
|===
| Оператор | Значење
| `<`      | Помало
| `\<=`    | Помало или еднакво
| `>`      | Поголемо
| `>=`     | Поголемо или еднакво
| `==`     | Еднаквост
| `!=`     | Не еднаквост (различно)
|===

=== Логички оператори
Се користат најчесто во комбинација со релационите оператори за формирање на сложени логички изрази, кои повторно враќаат резултат 0 или 1

[options="header",cols="^,3"]
|===
| Оператор | Операција
| `&&`     | Логичко *И* (AND)
| `\|\|`   | Логичко *ИЛИ* (OR)
| `!`      | Негација
|===
Пример:

[source,c]
----
int a = 5 && 0; // a = 0;
a = 2 && 5;     // a = 1;
a = 0 || 5;     // a = 1;
a = !0;         // a = 1;
a = !5;         // a = 0;
----

=== Дополнителни оператори

* Оператор за доделување =
* Оператори за инкрементирање и декрементирање (++, --)
** `++` инкрементирање (зголемување на вредноста на операндот за 1)
** `--` декрементирање (намалување на вредноста на операндот за 1)
* Користење на операторите + и – на унарен начин

[source,c]
----
X = + Y;
X = - Y;
----

* Двојни оператори
** Комбинација од оператор за доделување и друг оператор (+=, -=, *=, /=, %=)

=== Оператор за доделување `=`
* Сите изрази имаат вредност, дури и оние кои содржат =
* Вредноста на таков израз е вредноста на изразот кој се наоѓа на десна страна
* Затоа е можно и доделување од следниот облик:

[source,c]
----
 x = (y = 10) * (z = 5);
 x = y = z = 20;
----

=== Оператори за инкрементирање и декрементирање 

* Оператор за инкрементирање ++ (зголемување на вредноста на операндот за 1)
* Оператор за декрементирање --(намалување на вредноста на операндот за 1)
* Можат да бидат зададени во префикс или постфикс нотација:

==== Префикс 

Вредноста на променливата се зголемува пред да се пресмета изразот во која таа учествува
  
[source,c]
----
a = ++b;
----
	
==== Постфикс 

Вредноста на променливата се зголемува откако ќе се пресмета изразот

[source,c]
----
a = b++;
----

=== Двојни оператори
 
* Оператор `+=`

[source,c]
----
a += 5; // a = a + 5;
a += b * c; // a = a + b * c;
----
* Оператор `-=`

[source,c]
----
a -= 3; // a = a – 3;
----
* Оператор `*=`

[source,c]
----
a *= 3; // a = a * 3;
----
* Оператор `/=`

[source,c]
----
a /= 3; // a = a / 3;
----
* Оператор `%=`

[source,c]
----
a %= 3; // a = a % 3;
----

== Примери

=== Работа со променливи и доделување вредности

[source,c]
----
include::{source_dir}/ex3_1.c[]
----

=== Промена на вид на вредност – `cast` операција

.Формат
[source,c]
----
(podatocen tip) vrednost
----

.Пример
[source,c]
----
int i;
double d = 7.28;	
i = (int) d;
----

.Пример
[source,c]
----
(int) 5.56              // 5.56 во 5
(long) 8.28             // 8.28 во 8L
(double) 2              // 2 во 2.0
(char) 70               // 70 во char чиј код е 70 ('F')
(unsigned short) 3.14   //3.14 во 3 (unsigned short)
----

=== Претворање во друг тип

Манипулирање со спецификатор за конверзија **`%f`** и со оператор за делење

[source,c]
----
include::{source_dir}/ex3_2.c[]
----

=== Кастирање

* Во претходниот пример беше искористен каст оператор (оператор кој овозможува преминување од еден во друг тип):

[source,c]
----
kol = (float) integer1 / integer2; 
----

* Бидејќи `integer1` и `integer2` се цели броеви, резултатот кој ќе се добиеше по целобројното делење не ќе беше она што го очекувавме. Значи, барем една од тие вредности на `integer1` или `integer2` требаше некако да се претвори во реален број. Тоа ни го овозможи операторот `(float)`, кој `integer1` го претвори во реален број, а со тоа и целото делење се претвори во делење на реални броеви.
* Истиот ефект на кастирање на `int` во `double` може да се постигне и со множење на променливата со `double` константа `1.0`

[source,c]
----
kol = 1.0 * integer1 / integer2;
----

== Задачи

=== Задача 1

Да се напише програма која чита знак од тастатура и во зависнот од тоа дали е мала или голема буква печати 1 или 0, соодветно.

TIP: Користете логички и релациони оператори за тестирање на ASCII вредноста на знакот.

* Бонус: Направете проверка дали знакот е цифра


.Решение 1
[source,c]
----
include::{source_dir}/p3_1.c[]
----

.Решение на бонусот

[source,c]
----
rez = (ch >= '0') && (ch <= '9');
----

=== Задача 2

Да се напише програма која ќе чита два цели броеви (x, y) од тастура и на компјутерскиот екран ќе го испечати резултатот (z) од следниот израз

    z = x++ + --y + (x<y)

Каква вредност ќе има `z` за `x = 1`, `y = 2`?

.Решение 2
[source,c]
----
include::{source_dir}/p3_2.c[]
----

.Што ќе се случи во оваа ситуација:

[source,c]
----
z = x++ + --y + x<y;
----

=== Задача 3

* Нека е дадено:

	r = (x<y || y<z++)
	
	Каква вредност ќе има r за x=1, y=2, z=3?
	Каква вредност ќе има z?
	
* Нека е дадено:

	r = (x>y && y<z++)
	
	Каква вредност ќе има r за x=1, y=2, z=3?
	Каква вредност ќе има z?

.Решение 3
[source,c]
----
include::{source_dir}/p3_3.c[]
----

.Излез
----
r=1, z=3

r=0, z=3
----

=== Задача 4

* Нека е дадено:

[source,c]
----
include::{source_dir}/p3_4a.c[]
----	

Каква вредност ќе има `y` за `x=5`?

.Излез

y=1

* Нека е дадено:

[source,c]
----
include::{source_dir}/p3_4b.c[]
----	
    
Каква вредност ќе има `z` за `x=5`, `y=6`?

.Излез
----
z=2
----

=== Задача 5

Да се напише програма каде од тастатура ќе се внесе цена на производ, а потоа ќе ја испечати неговата цена со пресметан ддв.

TIP: ДДВ е 18% од почетната цена

.Решение 5
[source,c]
----
include::{source_dir}/p3_5.c[]
----

=== Задача 6

Да се напише програма каде од тастатура ќе се внесе цена на производ, број на рати на кои се исплаќа и камата (каматата е број изразен во проценти од 0 до 100). Програмата треба да го испечати износот на ратата и вкупната сума што ќе се исплати за производот

TIP: Пресметајте ја целата сума, па потоа ратата.


.Решение 6
[source,c]
----
include::{source_dir}/p3_6.c[]
----

=== Задача 7

Да се напише програма каде од тастатура ќе се внесе трицифрен цел број. Програмата ќе ја испечати најзначајната и најмалку значајната цифра од бројот

* Пример: Ако се внесе следниот бројот 795, програмата ќе испечати:
----
Najznacajna cifra e 7, a najmalku znacajna e 5.
----

TIP: Искористете целобројно делење и остаток од делење. 


.Решение 7
[source,c]
----
include::{source_dir}/p3_7.c[]
----

=== Задача 8

Да се напише програма каде од тастатура ќе се внесе датумот на раѓање во формат (ddmmgggg). Програмата на компјутерскиот екран ќе го испечати денот и месецот на раѓање.

.Пример: 
Ако се внесе следниот број 18091992, програмата ќе испечати:
          	18.09

TIP: Искористете целобројно делење и остаток од делење.

.Решение 8
[source,c]
----
include::{source_dir}/p3_8.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_av3_src.zip[Source code ZIP]
