# Структурно програмирање
Аудиториски вежби 10
v1.0, 2 Декември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/av10
== Текстуални низи (стрингови)

=== Потсетување од предавања

==== Функции за работа со текстуални низи од библиотеката `<string.h>`
---
_Функции за менување на текстуални низи:_

* `strcpy()` - копирање на една текстуална низа во друга
* `strncpy()` - копирање на n бајти од една текстуална низа во друга
* `strcat()` - надоврзува една текстуална низа на крајот на друга
* `strncat()` - надоврзува n бајти од една текстуална низа на крајот на друга

---
_Функции за менување на меморијата:_

* `memset()` - пополнува низа со одреден бајт 

---
_Функции за претворање на текстуални низи во броеви:_

* `atof()` - претвора текстуална низа во децимален број
* `atoi()` - претвора текстуална низа во цел број 

---
_Функции за испитување на текстуални низи:_

* `strlen()` - ја враќа должината на дадена текстуална низа
* `strcmp()` - споредува две текстуални низи
* `strncmp()` - споредува n бајти од две текстуални низи
* `strchr()` - го наоѓа првото појавување на даден знак во текстуална низа
* `strrchr()` - го наоѓа последното појавување на даден знак во текстуална низа
* `strspn()` - во текстуална низа го наоѓа првото појавување на знак кој не припаѓа на специфицирано множество од знаци
* `strcspn()` - во текстуална низа го наоѓа последното појавување на знак кој не припаѓа на специфицирано множество од знаци
* `strpbrk()` - во текстуална низа го наоѓа првото појавување на знак кој припаѓа на специфицирано множество од знаци
* `strstr()` - во текстуална низа го наоѓа првото појавување на дадена подниза

==== Функции за работа со знаци од библиотеката `<ctype.h>`
---
_Функции за работа со единечен знак:_

* `isalnum()` - проверува дали даден знак е алфанумерички (буква или цифра)
* `isalpha()` - проверува дали даден знак е буква
* `iscntrl()` - проверува дали даден знак е контролен знак
* `isdigit()` - проверува дали даден знак е декадна цифра
* `isxdigit()` - проверува дали даден знак е хексадекадна цифра
* `isprint()` - проверува дали даден знак може да се печати
* `ispunct()` - проверува дали даден знак е интерпункциски знак
* `isspace()` - проверува дали даден знак е празно место
* `islower()` - проверува дали даден знак е мала буква
* `isupper()` - проверува дали даден знак е голема буква
* `tolower()` - претвора дадена голема буква во соодветната мала буква
* `toupper()` - претвора дадена мала буква во соодветната голема буква
* `isgraph()` - проверува дали даден знак има локална графичка репрезентација

---

=== Задача 1

Да се напише функција што ќе одредува колку пати даден знак се наоѓа во даден стринг. Знакот за споредување и стрингот се внесуваат од тастатура. 

==== Пример

За стрингот 

`HELLO FINKI`

знакот `L` се појавува 2 пати.

.Решение `p10_1.c`
[source,c]
----
include::{source_dir}/p10_1.c[]
----

=== Задача 2

Да се напише функција што ќе ја одредува должината на една текстуална низа.

Да се даде итеративно и рекурзивно решение.

==== Пример

Ако на функцијата како аргумент и се предаде стрингот 

`zdravo!` 

тогаш таа треба да врати: `7`

.Решение `p10_2.c`
[source,c]
----
include::{source_dir}/p10_2.c[]
----

=== Задача 3

Да се напише програма која ќе ја отпечати поднизата на дадена текстуална низа (што се внесува од тастатура) определена со позицијата и должината, што како параметри се внесуваат од тастатура. Поднизата започнува од знакот што се наоѓа на соодветната позиција во текстуалната низа, броејќи од лево.

==== Пример

Ако од тастатура се внесе: 

`banana` 

позиција: `3` 

должина: `4` 

тогаш програмата треба да отпечати: `nana`

.Решение `p10_3.c`
[source,c]
----
include::{source_dir}/p10_3.c[]
----

=== Задача 4
Да се напише функција која ќе одредува дали една текстуална низа е подниза на друга текстуална низа. 

==== Пример
`face` 

е подниза на 

`Please faceAbook`

.Решение `p10_4.c`
[source,c]
----
include::{source_dir}/p10_4.c[]
----

=== Задача 5
Да се напише функција која ќе проверува дали дадена текстуална низа е палиндром.

Една текстуална низа е *палиндром* ако таа се чита исто од лево на десно и од десно на лево.
 
==== Примери за палиндроми 
----
dovod
ana
kalabalak
----

.Решение `p10_5.c`
[source,c]
----
include::{source_dir}/p10_5.c[]
----

==== Задача 5-а (*за дома*)
Да се напише функција која ќе проверува дали дадена реченица е палиндром. При проверката да се игнорираат празните места, интерпункциските знаци, а соодветните мали и големи букви да се сметаат за еднакви (`A` == `a`, `B` == `b`, итн.).
 
==== Примери за реченици - палиндроми 
----
A man, a plan, a canal, Panama.
Never odd or even.
Rise to vote sir!
----
 
=== Задача 6
Да се напише функција која за дадена текстуална низа ќе одредува дали таа е доволно сложена за да биде лозинка. 

Секоја лозинка мора да содржи барем една буква, барем една цифра и барем еден специјален знак.

==== Пример
`zdr@v0!` е валидна лозинка.

`zdravo` не е валидна лозинка.

.Решение `p10_6.c`
[source,c]
----
include::{source_dir}/p10_6.c[]
----

=== Задача 7
Да се напише функција која во стринг што и се предава како влезен параметар ќе ги промени малите букви во големи и обратно, и ќе ги отстрани сите цифри и специјални знаци.

==== Пример
За низата: 

`0v@ePr1m3R` 

треба да се добие: 

`VEpRMr`

.Решение `p10_7.c`
[source,c]
----
include::{source_dir}/p10_7.c[]
----

=== Задача 8

Да се напише функција која во дадена текстуална низа ќе ги отстранува празните места на почетокот и крајот од низата.

==== Пример
За низата: 

"   make trim   " 

треба да се добие: 

"make trim"

.Решение `p10_8.c`
[source,c]
----
include::{source_dir}/p10_8.c[]
----


include::parts/footer.adoc[]

link:{sources_zip}/sp_av10_src.zip[Source code ZIP]
