# Структурно програмирање
Аудиториски вежби 7
v1.0, 14 Ноември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/av7
== Матрици

=== Задача 1

Да се напише програма која за матрица внесена од тастатура ќе ја пресмета разликата на збирот на елементите на непарните колони и збирот на елементите на парните редици. 
Матрицата не мора да биде квадратна.

.Решение `p7_1.c`
[source,c]
----
include::{source_dir}/p7_1.c[]
----

=== Задача 2

Да се напише програма која за матрица внесена од тастатура ќе ги замени елементите од главната дијагонала со разликата од максималниот и минималниот елемент во матрицата. 
Резултантната матрица да се испечати на екран.

.Решение `p7_2.c`
[source,c]
----
include::{source_dir}/p7_2.c[]
----

=== Задача 3

Да се напише програма која за квадратна матрица внесена од тастатура ќе испечати на екран дали таа е симетрична во однос на главната дијагонала.

.Решение `p7_3.c`
[source,c]
----
include::{source_dir}/p7_3.c[]
----

== Функции

=== Потсетување од предавања

==== Дефиниција на функција во C

[source,c]
----
tip ime(lista_na_formalni_argumenti) {
  telo_na_funkcijata
}
----

- tip - типот на вредноста која ја враќа функцијата
- ime - името на функцијата
- lista_na_formalni_argumenti - листата со формални аргументи ги содржи аргументите заедно со нивните типови, разделени со запирка
- telo_na_funkcijata - телото на функцијата ги содржи истите елементи како и самата `main()` функција

==== Повик на функција

[source,c]
----
ime(lista_na_argumenti);
----

- ime - името на веќе дефинираната функција
- lista_na_argumenti - листата на аргументи е со вистински аргументи кои што ако се повеќе ако се одделуваат со запирка

==== Пример на кориснички дефинирана функција

Да се напише програма во која со посебна функција се пресметува куб stem:[n^3] за вчитан природен број n.

.Пример `ex7_1.c`
[source,c]
----
include::{source_dir}/ex7_1.c[]
----

=== Функции од математичката библиотека `math.h`

- Во C постои стандардна математичка библиотека `math.h` која што содржи многу готови математички функции.
- За да се употребува, треба претходно да се вклучи со:
`#include <math.h>`
- Сите функции од стандардната библиотека `math.h` примаат аргументи од тип `double` и враќаат вредности од истиот тип.

=== Најчесто користени математички функции

[options="header",cols="^,^4"]
|===
| Функција     | Објаснување
| `sqrt(x)`    | квадратен корен од `x`  
| `exp(x)`     | експоненцијална функција  stem:[е^х]         
| `log(x)`     | природен логаритам од х (со основа е)
| `log10(x)`   | логаритам од х со основа 10
| `fabs(x)`    | апсолутна вредност од х
| `ceil(x)`    | заокружува х на најмалиот цел број не помал од х
| `floor(x)`   | заокружува х на најголемиот цел број не поголем од х
| `pow(x, y)`  | x на степен y
| `fmod(x, y)` | остаток од х/у како реален број
| `sin(x)`     | синус од х (во радијани)
| `cos(x)`     | косинус од х (во радијани)
| `tan(x)`     | тангенс од х (во радијани)
|===

==== Пример на користење на функција од `math.h`

Да се напише програма во која со посебна функција се пресметува куб stem:[n^3] за вчитан природен број n.

.Пример `ex7_2.c`
[source,c]
----
include::{source_dir}/ex7_2.c[]
----

=== Задача 1

Да се напише програма која ќе провери дали дадена низа од `n` елементи која се чита од стандарден влез е _строго растечка_, _строго опаѓачка_ или ниту строго растечка ниту строго опаѓачка.
Резултатот да се испечати на екран.

.Решение `p6_4.c`
[source,c]
----
include::{source_dir}/p6_4.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_av6_src.zip[Source code ZIP]