# Structured programming
Exercises 10
v1.0, 13 December, 2016
include::parts/attributes_en.adoc[]

:source_dir: ../../src/av10

== Strings

=== Remainders from lectures

==== String functions from `<string.h>`
---
_String mutation functions:_

* `strcpy()` - copy one string to another
* `strncpy()` - copy n bytes from one string to another, from `src` are copied or `nulls` are padded
* `strcat()` - concatenates string at the end of another
* `strncat()` - concatenates n bytes of one string to another

---
_Memory changing functions:_

* `memset()` - filles array with some byte

---
_Functions for conversion string to numbers:_

* `atof()` - converts string to decimal number
* `atoi()` - converts string to integer number

---
_String checking functions:_

* `strlen()` - returns the length of the string
* `strcmp()` - compares two strings
* `strncmp()` - compares n bytes from two strings
* `strchr()` - finds the first occurrence of given character in some string
* `strrchr()` - finds the last occurrence of given character not in a set of chars
* `strspn()` - finds the first occurrence of given character in some string in a given set of chars
* `strpbrk()` - finds the first occurrence of given character in some string in a given set of chars
* `strstr()` - finds the first occurrence of string in other string

==== Functions for characters from the library `<ctype.h>`
---
_Functions for characters:_

* `isalnum()` - checks if the character is alphanumeric (letter or number)
* `isalpha()` - checks if the character is letter
* `iscntrl()` - checks if the character is control
* `isdigit()` - checks if the character is digit
* `isxdigit()` - checks if the character is hex digit
* `isprint()` - checks if the character is printable
* `ispunct()` - checks if the character is punctuation
* `isspace()` - checks if the character is printable
* `islower()` - checks if the character is lowercase
* `isupper()` - checks if the character is uppercase
* `tolower()` - converts to lowercase
* `toupper()` - converts to uppercase
* `isgraph()` - checks if the character has local graphic representation

---

=== Problem 1

Write a function that will find how many times a given character occurs in given string.

.Example
For the string

`HELLO FINKI`

character `L` occurs 2 times.

.Solution `p10_1_en.c`
[source,c]
----
include::{source_dir}/p10_1_en.c[]
----

=== Problem 2

Write a function that will return the length of a string.

Also write a *recursive* solution.

.Example

For string

`zdravo!` 

it should return: `7`

.Solution `p10_2_en.c`
[source,c]
----
include::{source_dir}/p10_2_en.c[]
----

=== Problem 3

Write a program that will print substring from given string, determined with the position and the length as parameters read from SI.
The substring starts from the character on the position counted from left to right.

.Example

For the string:

`banana` 

position: `2`

length: `4`

the output is: `nana`

.Solution `p10_3_en.c`
[source,c]
----
include::{source_dir}/p10_3_en.c[]
----

=== Problem 4

Write a function that will check if one string is substring of some other string.

.Example

`face` is substring of `Please faceAbook`

.Solution `p10_4_en.c`
[source,c]
----
include::{source_dir}/p10_4_en.c[]
----

=== Problem 5

Write a function that will check if given string is palindrome. 
Palindrome is a string that is read same from left to right and from right to left.
 
.Examples for palindromes
----
dovod
ana
kalabalak
----

.Solution `p10_5_en.c`
[source,c]
----
include::{source_dir}/p10_5_en.c[]
----

==== Problem 5-а (*homework*)

Write a function that will check if given sentence is a palindrome. 
Ignore the empty spaces, punctuations characters and the case of letters.
 
.Examples for sentences palindromes

----
Jadejne i pienje daj!
A man, a plan, a canal, Panama.
Never odd or even.
Rise to vote sir!
----
 
=== Problem 6

Write a function that for a given string will if it's complex enough to become a password.
Every password must have at least one letter, one digit and one special character.

.Example

`zdr@v0!` is a valid password.

`zdravo` is not a valid password.

.Solution `p10_6_en.c`
[source,c]
----
include::{source_dir}/p10_6_en.c[]
----

=== Problem 7

Write a function that for will change the case of the letters and will remove all digits and special characters.

.Example
For the string:

`0v@ePr1m3R` 

the result should be:

`VEpRMr`

.Solution `p10_7_en.c`
[source,c]
----
include::{source_dir}/p10_7_en.c[]
----

=== Problem 8

Write a function that will trim a string (remove blanks at front and end of string).

.Example
For the string:
----
"   make trim   "
----
the output should be:

----
"make trim"
----

.Solution `p10_8_en.c`
[source,c]
----
include::{source_dir}/p10_8_en.c[]
----


include::parts/footer_en.adoc[]

link:{sources_zip}/sp_av10_src_en.zip[Source code ZIP]
