# Структурно програмирање
Аудиториски вежби 5
v1.0, 3 Октомври, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/av5
= Контролни структури за циклуси

== Задача 1
Да се напише програма за пресметување на сумата на сите парни двоцифрени броеви. Добиената сума се печати на екран.

.Решение:
[source,c]
----
include::{source_dir}/p5_1a.c[]
----

=== Задача 1б

Да се напише програма за пресметување на сумата на сите непарни двоцифрени броеви. Програмата ја печати сумата на екран во следниот формат: 

----
11 + 13 + 15 + 17 + ... + 97 + 99 = 2475
----

*Забелешка:* Програмата да се направи без користење на наредбата if

.Решение 1:
[source,c]
----
include::{source_dir}/p5_1b1.c[]
----


.Решение 2:
[source,c]
----
include::{source_dir}/p5_1b2.c[]
----

== Задача 2
Да се напише програма за пресметување на y = x^n за даден природен број n, n >= 1 и реален број x.

.Решение 1:
[source,c]
----
include::{source_dir}/p5_2a.c[]
----

.Решение 2:
[source,c]
----
include::{source_dir}/p5_2b.c[]
----

.Решение 3:
[source,c]
----
include::{source_dir}/p5_2c.c[]
----

.Решение 4:
[source,c]
----
include::{source_dir}/p5_2d.c[]
----

== Задача 3

Да се напише програма што од n броеви (внесени од тастатура) ќе го определи бројот на броеви што се деливи со 3, при делењето со 3 имаат остаток 1, односно 2.

*Забелeшка:* Задачата да се реши со `while, do…while` и `for`

.Решение со *while*:

[source,c]
----
include::{source_dir}/p5_3a.c[]
----

.Решение со *do ... while*:

[source,c]
----
include::{source_dir}/p5_3b.c[]
----

.Решение со *for*:

[source,c]
----
include::{source_dir}/p5_3c.c[]
----

== Задача 4 

Да се напише програма што на екран ќе ги испечати сите четири-цифрени броеви кај кои збирот на трите најмалку значајни цифри е еднаков со најзначајната цифра.

TIP: 4031 (4=0+3+1), 5131 (5=1+3+1)


.Решение:
[source,c]
----
include::{source_dir}/p5_4.c[]
----

== Задача 5

Да се напише програма што ќе ги испечати сите броеви од зададен опсег кои исто се читаат и одлево надесно и оддесно налево.

TIP: 12345 54321

.Решение:
[source,c]
----
include::{source_dir}/p5_5.c[]
----

== Задача 6

Да се напише програма што од непознат број на цели броеви што се внесуваат од тастатура ќе го определи бројот со максимална вредност. Програмата завршува ако наместо број се внесе знак што не е цифра.

.Решение:
[source,c]
----
include::{source_dir}/p5_6.c[]
----

== Задача 7

Да се напише програма што од непознат број на цели броеви што се внесуваат од тастатура ќе го определи бројот со максимална вредност. Притоа броевите поголеми од 100 не се земаат предвид т.е. се игнорираат. Програмата завршува ако наместо број се внесе знак што не е цифра.

.Решение:
[source,c]
----
include::{source_dir}/p5_7.c[]
----

== Задача 8

Да се напише програма што од непознат број на цели броеви што се внесуваат од тастатура ќе ги определи двата броја со најголеми вредности. Програмата завршува ако наместо број се внесе знак што не е цифра. 

TIP: Ако се внесат броевите 2 4 7 4 2 1 8 6 9 7 10 3 програмата ќе отпечати 10 и 9.

.Решение:
[source,c]
----
include::{source_dir}/p5_8.c[]
----

== Задача 9

Да се напише програма што од N цели броеви внесени од тастатура ќе ја определи разликата од сумите на броевите на парни и непарни позиции (според редоследот на внесување). Ако оваа разлика е помала од 10 на екран се печати "Dvete sumi se slicni" а во спротивно на екран се печати "Dvete sumi mnogu se razlikuvaat".

TIP: За броевите внесени од тастатура:

`2` 4 `3` 4 `2` 1 `1` 6 `1` 7

`suma_neparni_pozicii = 9`

suma_parni_pozicii = 22

На екран ќе се испечати: 
----
Dvete sumi mnogu se razlikuvaat
----


.Решение:
[source,c]
----
include::{source_dir}/p5_9.c[]
----

== Задача 10

Да се напише програма што од непознат број на цели броеви кои се внесуваат од тастатура ќе ги определи позициите (редните броеви на внесување) на двата последователни броја што ја имаат најголемата сума. Програмата завршува ако едно по друго (последователно) се внесат два негативни цели броја.

.Решение:
[source,c]
----
include::{source_dir}/p5_10.c[]
----

= Контролна структура за повеќекратно гранење (switch)

== Пример

[source,c]
----
include::{source_dir}/ex5_1.c[]
----

== Задача 1

Да се напише програма што за знак внесен од тастатура ќе одреди дали е самогласка, цифра или другo.

.Решение:
[source,c]
----
include::{source_dir}/p5_11.c[]
----


== Задача 2

Да се напише програма што ќе претставува едноставен калкулатор. Во програмата се вчитуваат два броја и оператор во формат:

----
broj1 operator broj2
----

По извршената операција во зависност од операторот, се печати резултатот во
формат:

----
broj1 operator broj2 = rezultat
----

.Решение:
[source,c]
----
include::{source_dir}/p5_12.c[]
----

== Задача 3

Да се напише програма што  ќе го пресмета просекот на еден студент, како и бројот на испити на што студентот паднал. Бројот на испити кои студентот ги полагал не е познат.

.Решение 1:
[source,c]
----
include::{source_dir}/p5_13a.c[]
----


.Решение 2:
[source,c]
----
include::{source_dir}/p5_13b.c[]
----


== Пример за реализација на (текст) мени

.Решение:
[source,c]
----
include::{source_dir}/ex5_2.c[]
----

== Задача за вежбање 1

Нека x = sin y се менува од 0,02 до 0,80 со чекор 0,01. Да се напише програма што ќе го табелира y во форма степени, минути и секунди.

𝑦=arctan⁡〖𝑥/√(1−𝑥^2 )〗

.Решение:
[source,c]
----
include::{source_dir}/p5_14.c[]
----

== Задача за вежбање 2

Да се напише програма за приближно пресметување на 𝜋 според `формулата за развој на Gregory–Leibniz`

----
1−1/3+1/5−1/7+1/9−…=𝜋/4

∑_(𝑛=0)^∞▒〖(−1)〗^𝑛/(2𝑛+1)=𝜋/4
----

* користејќи ги првите 100 члена.
* се додека апсолутната вредност на членот што се додава е поголема од 10-6


.Решение 1.1:
[source,c]
----
include::{source_dir}/p5_15a.c[]
----

.Решение 1.2:
[source,c]
----
include::{source_dir}/p5_15b.c[]
----

.Решение 2:
[source,c]
----
include::{source_dir}/p5_15c.c[]
----

== Задача за вежбање 3

Да се напише програма за приближно пресметување на 𝜋 користејќи го изразот 4∙arctan⁡1=𝜋 и развојот на arctan во ред.


.Решение:
[source,c]
----
include::{source_dir}/p5_16.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_av3_src.zip[Source code ZIP]