# Структурно програмирање
Аудиториски вежби 9
v1.0, 27 Ноември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/av9

== Потсетување од предавања

=== Што е покажувач

Покажувач е *податочен тип* кој што чува (покажува кон) одредена локација во меморијата. Оваа мемориска локација се чува преку нејзината адреса (позитивен цел број)

=== Декларација на покажувач

[source,c]
----
pointer_type *name;
----

.Пример
[source,c]
----
float *p;
----

_Вака декларираниот покажувач не знаеме каде покажува!!!_

=== За што служат покажувачите?
- брзо и ефикасно изминување на сложени податочни структури како низи и дрва, ...
- ефикасно пренесување на сложени аргументи во функции. Пренесување на низа, структура и слично
- пренесување на аргументи чии што вредности сакаме да останат во онаа состојба во која се наоѓаат по извршувањето на функцијата

== Задача 1

Да се напише функција која за низа од N цели броеви ќе ги пронајде почетокот и должината на најголемата растечка подниза.

.Пример:
За низата

2 3 *1 4 7 12* 7 9 1


ќе ја најде низата со почеток во индексот 2, со должина од 4


.Решение `p9_1.c`
[source,c]
----
include::{source_dir}/p9_1.c[]
----

== Задача 2

Да
се напише програма која влезната низа
\[
a_0, a_1, ... a_{n-1}
\]

ќе ја трансформира во излезната низа:
\[ b_0, b_1, b_2, ..., b_{n-1} \]

на следниот начин:
\[
b_0 = a_0 + a_{n-1}
b_1 = a_1 + a_{n-2}
.
.
.
b_{n-1} = a_{n-1} + a_0
\]

.Пример
Влезната низа
----
1 2 3 5 7
----

треба да се трансформира во

----
8 7 6 7 8
----


.Решение `p9_2.c`
[source,c]
----
include::{source_dir}/p9_2.c[]
----


== Задача 3

Да се напишат следните функции за пребарување во низа:

- Линеарно пребарување
- Бинарно пребарување

Потоа да се напише главна програма во која ќе се пополнува низа со броевите од 1 до 1 000 000, а потоа се генерира случаен број во овој опсег чија што позиција треба да се пронајде со повикување на двете функции за пребарување.

=== За дома:
За двете функции избројте го и споредете го бројот на потребни итерации за пронаоѓање на бројот.

.Решение `p9_3.c`
[source,c]
----
include::{source_dir}/p9_3.c[]
----

=== За дома:
Да се напише рекурзивна функција за бинарно пребарување на низа.



== Задача 4

Да се напишат фунции за сортирање на низа со помош на следните методи за сортирање:
- Метод на меурче (Bubble sort)
- Метод со избор на елемент (Selection sort)
- Метод со вметнување (Insertion sort)

Да се напишат функции за внесување и печатење на елементите на една низа и да се напише главна програма во која се тестираат сите методи за сортирање.

=== Bubble sort
.Решение `p9_4.c`
[source,c]
----
include::{source_dir}/p9_4.c[lines=3..11]
----
Се започнува од првиот елемент и се споредуваат секои два соседни додека не се дојде до последниот елемент. При секое споредување, ако претходниот има поголема вредност, тогаш си ги заменуваат местата. Така најголемиот елемент се доведува на последната позиција во низата. Се повторува истата постапка од 1-от до претпоследниот елемент во низата, така што сега на претпоследната позиција ќе исплива елемент помал од најголемиот елемент во низата итн. На крајот се споредуваат само 1-от и 2-от елемент од низата.

=== Selection sort
.Решение `p9_4.c`
[source,c]
----
include::{source_dir}/p9_4.c[lines=13..28]
----

Се  пронаоѓа најмалиот елемент во низата и истиот се заменува со првиот елемент. Потоа, првиот елемент на низата се игнорира (бидејќи се знае дека тој е најмал) и рекурзивно се сортира преостанатата подниза (од вториот елемент, па до крајот). Постапката се повторува сé дури не остане само еден елемент. Тоа е граничниот случај – се престанува со сортирањето

=== Insertion sort
.Решение `p9_4.c`
[source,c]
----
include::{source_dir}/p9_4.c[lines=30..41]
----

Со овој метод се сортира на тој начин што секој елемент се вметнува на соодветната позиција, од што и доаѓа самото име. Во првата итерација, вториот елемент a[1] се споредува со првиот елемент a[0]. Во втората итерација третиот елемент се споредува со првиот и вториот. Генерално, во секоја итерација елементот се споредува со сите елементи пред него. Ако при споредбата се покаже дека тој елемент треба да се вметне на соодветната позиција, тогаш се создава простор со поместување на сите елементи десно од тој елемент за еден и се вметнува елементот. Оваа процедура се повторува за секој елемент во низата.

=== Целокупното решение

.Решение `p9_4.c`
[source,c]
----
include::{source_dir}/p9_4.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_av9_src.zip[Source code ZIP]
