# Структурно програмирање
Аудиториски вежби 8
v1.0, 20 Ноември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/av8
== Рекурзивни функции

Функциите во програмскиот јазик Ц може да повикуваат други функции. Ова повикување може да оди во произволна длабочина.

Доколоку една функција се повикува сама себе, тогаш тоа се нарекува *рекурзивен повик*, односно тој начин на повикување се нарекува *рекурзија*

_Пример за рекурзивна функција:_

[source,c]
----
include::{source_dir}/ex8_1.c[lines=4..10]
----

=== Задача 1

Да се пресмета збирот:
\[
1! + (1+2)! + (1+2+3)! + ... + (1+2+...+n)!
\]
притоа: 

- користете *рекурзивна функција* за пресметување на збирот на првите k природни броеви.
- користете *рекурзивна функција* за пресметување на факториел на еден природен број.

.Решение `p8_1.c`
[source,c]
----
include::{source_dir}/p8_1.c[]
----

=== Задача 2

Да се напише програма која за даден природен број ја пресметува разликата помеѓу најблискиот поголем од него прост број и самиот тој број.

Програмата треба да користи *рекурзивна* функција за наоѓање на соодветниот прост број, која пак треба да користи рекурзивна функција за проверка дали даден број е прост број.

==== Пример

Ако се внесе 573, програмата треба да испечати 577 - 573 = 4

.Решение `p8_2.c`
[source,c]
----
include::{source_dir}/p8_2.c[]
----

=== Задача 3

Да се напише програма што ќе ја испишува вредноста на n-тиот член на низата дефинирана со:
\[
   \begin{array}{l}
   x_1 = 1\\
   x_2 = 2\\ 
   \vdots\\
   x_n = \frac{n - 1}{n}x_{n - 1} + \frac{1}{n}x_{n - 2}
   \end{array}
\]

.Решение `p8_3.c`
[source,c]
----
include::{source_dir}/p8_3.c[]
----

=== Задача 4
Да се напише рекурзивна функција која ќе го пресметува збирот на цифрите на еден број.

==== Пример:
----
sumDigits(126) -> 9
sumDigits(49) -> 13
sumDigits(12) -> 3
----

.Решение `p8_4.c`
[source,c]
----
include::{source_dir}/p8_4.c[]
----

=== Задача 5
За даден број n, да се напише *рекурзивна функција* која ќе ги изброи појавувањата на цифрата 8. Притоа, доколку до некоја цифра 8 има уште една цифра 8 веднаш лево од неа, нејзиното појавување се брои двојно

==== Пример: 
----
count8(8) -> 1
count8(818) -> 2
count8(8818) -> 4
----

.Решение `p8_5.c`
[source,c]
----
include::{source_dir}/p8_5.c[]
----

=== Задача 6
Да се напише програма која што за дадена низа од природни броеви (која што се внесува од тастатура) ќе го отпечати најголемиот заеднички делител (НЗД) на нејзините елементи.  Програмата задолжително треба да содржи *рекурзивна функција* за пресметување на НЗД на два природни броја.

==== Пример
----
48 36 120 72 84
----

На екран треба да се отпечати:

----
NZD na elementite na ovaa niza e 12}
----

* НЗД за два броја може да се пресмета со користење на Евклидовиот алгоритам.
* За да се пресмета НЗД на броевите m и n, се пресметува остатокот при делење на m со n.
** ако остатокот не е 0, се пресметува остатокот при делење на n со m % n
** постапката се повторува се додека се добиваат ненеулти остатоци
** ако остатокот е 0, НЗД на двата броја е последниот пресметан ненулти остаток.

==== Пример
----
NZD(20, 12)
20 % 12 = 8
12 % 8 = 4
8 % 4 = 0

NZD(20, 12) = 4
----

.Решение `p8_6.c`
[source,c]
----
include::{source_dir}/p8_6.c[]
----


=== Задача 7 (*За Дома*)
Да се напише програма која за дадена низа од цели броеви (која се внесува од тастатура), ќе го отпечати најмалиот заеднички содржател (НЗС) на нејзините елементи. Програмата треба задолжително да содржи рекурзивна функција за пресметување на НЗС на два броја.

==== Пример:
За низата: `18 12 24 36 6` на екран треба да се отпечати:
----
NZS na elementite na ovaa niza e 72
----

=== Задача 8

Да се напише програма која за дадена низа од цели броеви (која што се внесува од тастатура) ќе го отпечати збирот на елементите од низата. Програмата треба да содржи рекурзивна функција за наоѓање на збирот на елементите во дадена низа.

.Решение `p8_8.c`
[source,c]
----
include::{source_dir}/p8_8.c[]
----

=== Задача 9 (*За Дома*)

Да се напише програма која за дадена низа од цели броеви (која што се внесува од тастатура) ќе го отпечати најголемиот елемент. Програмата треба да содржи рекурзивна функција за наоѓање на најголем елемент во дадена низа.

==== Пример
За низата:

`5 8 3 12 9 6`

На екран треба да се отпечати:

`Najgolem element vo nizata e 12`


include::parts/footer.adoc[]

link:{sources_zip}/sp_av8_src.zip[Source code ZIP]
