# Structured programming
Exercises 11
v1.0, 15 December, 2016
include::parts/attributes_en.adoc[]

:source_dir: ../../src/av11

== Files

=== Remainders from lectures

* Processing files includes writing, reading and changing contents of files to some standard media as disk.
* Processing files in C is done using the struct `FILE` defined in `stdio.h`.
* To start processing the file first it must be open using the function `fopen` that returns pointer to the struct `FILE*`.

==== Opening file for reading/writing
---
_Function for opening file:_

`FILE* fopen(const char* file_path, const char* mode);`

`file_path` - full path of the file we want to open
 
`mode` - opening mode

==== Modes of opening files

[options="header",cols="^,5"]
|===
| *Mode*    | *Meaning*
| `r`      | Opens existing file only for reading
| `w`      | Opens existing file for writing (the file must exist)
| `a`      | Opens existing file for appending (the file must exist)
| `r+`     | Opens file for reading and writing at the beginning of the file
| `w+`     | Opens file for reading and writing (deletes the contents of the file)
| `a+`     | Opens file for reading and writing (appends at the end of the file if it exists)
|===
---

.Example of opening file

[source,c]
----
FILE* fp = fopen("test.txt", "r");
----

* Opens the file "test.txt" in reading mode.
* To open in binary mode `b` should be appended at the mode of opening ex `rb`.

==== Closing file

---
_Function for closing file:_

`int fclose(FILE* fp);`  

`fp` - pointer to FILE we want to close

.Example of closing file

[source,c]
----
fclose(fp);
----

* After the end of processing, the file should be closed using the function `fclose()`
* Calling this functions closes the file associated with the file pointer `fp` passed as argument


==== Reading and writing from/to file
---
_Functions for reading from file:_

`int fscanf(FILE* fp, "format_specifier", arguments_list);`

`int fgetc(FILE* fp);`
 
`char* fgets(char* str, int num, FILE* fp);`

---
_Functions for writing to files:_

`int fprintf(FILE* fp, "format_specifier", arguments_list);`

`int fputc(char c, FILE* fp);`
 
`int fputs(const char* str, FILE* fp);`
---

=== Problem 1

Write a program that for given textual file `text.txt` will find the ratio of vowel/consonants.

.Example

If the file `text.txt` has the following contents:

----
Hello, how are you?
I'm OK. How about you?
I'm fine too.
----

then the output should be:
----
Ratio vowels/consonats: 20/18 = 1.11
----

.Solution `p11_1_en.c`
[source,c]
----
include::{source_dir}/p11_1_en.c[]
----

=== Problem 2

Write a program that each row from given input file `input.txt` will copy in other file `output.txt`, so that for each row from `input.txt` will add one more with the length of that row.
Each row can have at most 80 characters.

.Example
If the file `input.txt` has the following contents:

----
I'm learning Structured Programming.
When is the second midterm?
I don't know, still it is not published on the web.
----

тогаш по извршувањето на програмата содржината на датотеката `izlezna.txt` треба да биде следнава:

----
36
I'm learning Structured Programming.
27
When is the second midterm?
51
I don't know, still it is not published on the web.
----

.Solution `p11_2_en.c`
[source,c]
----
include::{source_dir}/p11_2_en.c[]
----

=== Problem 3

Write a program that will read elements of a matrix written in text file with name `mat1.txt`.
In the first line of the file are written the number of rows and columns of the matrix.
Each element of the matrix is floating point number written in separate line.
The transposed matrix write in a new output file `mat2.txt` using the same format.

.Example
If the file `mat1.txt` has the following content:

----
3 4
2.1
3.2
4.3 
5.4
1.1
2.2
3.3
4.4
6.0
5.5
3.9
1.8
----

then at the end of the execution of the program, the file `mat2.txt` should have the following content:

----
4 3
2.1
1.1
6.0
3.2
2.2
5.5
4.3
3.3
3.9
5.4
4.4
1.8
----

.Solution `p11_3_en.c`
[source,c]
----
include::{source_dir}/p11_3_en.c[]
----

=== Problem 4

Given is the file `SP_example.txt`.
Write a program that will read the file and will print the number of rows with more than 10 vowels, and the total vowels in the file.

.Example
If the file `SP_example.txt` has the following content:

----
Zdravo, kako si?
Eve, dobro sum. A ti?
I jas dobro. Kako se tvoite? Ima li neshto novo?
Dobri se i tie. Si kupiv avtomobil.
----

then the program should print:

----
Total 2 rows have more than 10 vowels.
The file has total 38 vowels.
----

.Solution `p11_4_en.c`
[source,c]
----
include::{source_dir}/p11_4_en.c[]
----

=== Problem 5

Write a program that for given file `words.txt` will print all the words that have three or more equal letters (some letter occurs three or more times).
The comparison of letters is not case sensitive.
At the end it should print the count of words that satisfy this condition.

The file contains one word per row.
Each word is composed only from letters.
The maximal length of a word is 20 chars.
 
.Example
If the file `words.txt` has the follwoing content:

----
banana
jabolko
Obratnoto
binarnata
dekadniot
Kopakabana
----

then the program should print:

----
banana
Obratnoto
binarnata
Kopakabana
Total 4 words.
----

.Solution `p11_5_en.c`
[source,c]
----
include::{source_dir}/p11_5_en.c[]
----

=== Problem 6

Write a program that will print the count of occurrences of a word composed only from digits (read from SI) in a file named `dat.txt`.

.Example
If we read the word

`123`

and if the file `dat.txt` has the following content:

----
Zdravo 123, kako si?
Eve 321, dobro sum. A ti?
I jas dobro. Kako se tvoite 123? Ima li neshto novo? 123
Dobri se i tie. Si kupiv avtomobil.
----

then it should print:

----
The word 123 occurs 3 times in the file.
----

.Solution `p11_6_en.c`
[source,c]
----
include::{source_dir}/p11_6_en.c[]
----

include::parts/footer_en.adoc[]
link:{sources_zip}/sp_av11_src_en.zip[Source code ZIP]
