# Structured programming
Example midterm problems
v1.0, 3 November, 2016
include::parts/attributes_en.adoc[]

:source_dir: ../../src/mt
== Problems

=== Easy problem

Write a program that will read characters from SI while the character `.` is read. 
Than the program should print on the standard output the character with most consecutive occurrences. 
If there are more characters with same number of consecutive occurrences print the first of them.

.Example

----
Input:
thiiis shooould beeeeee an easy problem
Output:
e 18
----

=== Cyclic numbers

A whole number is "cyclic" if for each of the digits of the number the following rules apply:

* the two neighboring digits (left and right of the digit) are bigger than the digit;
or
* the two neighboring digits (left and right of the digit) are smaller than the digit
* if the digit does not have two neighboring digits (i.e. it is the most significant or least significant digit) than it is not checked for the rule (left out)

From SI read unknown number of integers (until there is something that can not be interpreted as a integers). 
From all integers entered from SI print out and count only the cyclic numbers.

_Explanation_:
----
3241 is a number with cyclic digits ( 3 > 2 < 4 > 1)
121435 is a number with cyclic digits ( 1 < 2 > 1 < 4 > 3 < 5)
565794 - is NOT a number with cyclic digits (5 < 6 > 5 < 7 < 9 > 4)
32112 - is NOT a number with cyclic digits (3 > 2 > 1 = 1 < 2 )
----

WARNING: Arrays are not allowed! Solve the problem without using arrays.

.Solution `p1_mt1.c`
[source,c]
----
include::{source_dir}/p1_mt1.c[]
----
=== Consecutive pairs with m digits

Read from SI an integer m, and then unknown number of integers.
Print the lengths of the sequences containing at least two consecutive integers such as:

* next number is greater then the previous
* each number is composed of m digits.

NOTE: _The problem should be solved without using arrays._

.Example
----
Input:
3 45 456 567 784 67890 12 543 321 462 2 23 34 567 765 898 975
Output:
3 2 4
----            

.Solution `p2_mt1.c`:
[source,c]
----
include::{source_dir}/p2_mt1.c[]
----

include::parts/footer_en.adoc[]

link:{sources_zip}/sp_mt_en_src.zip[Source code ZIP]
