# Структурно програмирање
Пример задачи од 2 колоквиум
v1.0, 19 Декември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../src/kol2

== Задачи

=== Задача 1

За еден природен број `a` велиме дека е порамнување на друг природен број `b` ако и само ако цифрите еднакви на 9 во бројот `b` се заменети со цифрата 7 во бројот `a`.
Пример. Бројот 734775 е порамнување на бројот 934795.

Од стандарден влез се внесуваат непознат број на цели броеви (не повеќе од 100), се додека не се внесе нешто што не може да се интерпретира како цел број.
Ваша задача е да ги отпечатите најмалите 5 од порамнувањата на сите внесени броеви, по редослед од најмалиот кон најголемиот.

NOTE: Доколку се внесат помалку од 5 броеви, тогаш печатите толку броеви колку што се соодветно внесени.
Наоѓањето на порамнувањето на даден број треба да се реализира во посебна рекурзивна функција `poramnet(int a)`.

.Пример.
За броевите: 9592, 69403, 100007, 6, 987, 6977, 33439, треба да се најдат нивните порамнувања (тоа се: 7572, 67403, 100007, 6, 787, 6777 и 33437, соодветно), и да се отпечатат најмалите 5 од нив по овој редослед: 6 787 6777 7572 33437.

WARNING: ЗАБРАНЕТО е користење на глобални променливи.

.Решение `p_kol2_1.c`
[source,c]
----
include::{source_dir}/p_kol2_1.c[]
----

=== Задача 2

За квадратна матрица A со димензии n x n, од стандарден влез се внесува бројот n (n >=2) и елементите на матрицата (реални броеви). 
Нека X e збирот од елементите под главната дијагонала во матрицата А. 
Нека Y е збирот од елементите под споредната дијагонала во матрицата А. 
Да се креира нова матрица B на следниот начин: 

- сите елементи од главната дијагонала во матрицата B треба да имаат вредност X
- сите елементи од споредната дијагонала во матрицата B треба да имаат вредност Y
- ако даден елемент припаѓа и на главната и на споредната дијагонала во матрицата B, тогаш неговата вредност e X+Y
- сите останати елементи во матрицата B имаат вредност 0

Новата матрица B да се испечати на стандарден излез.

.Пример:
----
Матрица A
5         5.5          6          1.2          2.5
8         95.1         21.3       13           0.2
34        4.1          37.4       22           6
4.1       5.5          0.7        7            0
42        1.1          3.2        7.5          1.8
Матрица B
110.2          0          0          0          49.5
0              110.2      0          49.5       0
0              0          159.7      0          0
0              49.5       0          110.2      0
49.5           0          0          0          110.2
----

.Решение `p_kol2_2.c`
[source,c]
----
include::{source_dir}/p_kol2_2.c[]
----

=== Задача 3

Во дадена датотека `dat.txt` да се најде најдолгиот ред во кој има барем 2 цифри.
На стандарден излез да се испечатат знаците од најдолгиот ред кои се наоѓаат помеѓу првата и последната цифра (заедно со тие 2 цифри) во истиот редослед.
Доколку има повеќе такви редови се печати последниот.
Се претпоставува дека ниту еден ред на датотеката не е подолг од 100 знаци.

.Пример
----
Влез:
dat.txt:
aaa123aa222aa2aaa23aaaaa22
aaaaaaaaaaaa 23aaaa
123 aaa aaa aaa aaa 12345 aaa aaa 2a

Излез:
123 aaa aaa aaa aaa 12345 aaa aaa 2
----            

.Решение `p_kol2_3.c`
[source,c]
----
include::{source_dir}/p_kol2_3.c[]
----

=== Задача 4

Од стаднарден влез се читаат N низи од знаци (стрингови) не подолги од 80 знаци.
На почетокот на програмата се читаат два цели броеви:  N - бројот на низи од знаци кои ќе се читаат и X - поместување.
Секоја од вчитаните низи од знаци треба да се трансформира на тој начин што секоја од малите и големите букви (a-z, A-Z) се заменува со истата буква поместена X места понапред во азбуката (az).
Ако се надмине опсегот на буквите во азбуката, се продолжува циклично од почетокот на азбуката.
Трансформираната низа да се отпечати на СИ.
Трансформацијата да се имплементира со посебна рекурзивна функција.

.Пример:
`Welcome` -> трансформирано со поместување 5 -> `Bjqhtrj`

.Решение `p_kol2_4.c`
[source,c]
----
include::{source_dir}/p_kol2_4.c[]
----

=== Задача 5

Да се напише програма која вчитува матрица со димензии MxN (макс. 100x100).
На почетокот се внесуваат димензиите на матрицата, а потоа и елементите на матрицата кои се само вредностите 1 и 0. Програмата треба да изброи и отпечати на СИ во колку од редиците и колоните има барем 3 последователни елементи со вредност 1.

.Пример
----
1    1     1    0
1    0     1    1
1    0     0    1
1 ред + 1 колона = 2
----

.Решение `p_kol2_5.c`
[source,c]
----
include::{source_dir}/p_kol2_5.c[]
----

=== Задача 6

Во дадена датотека `broevi.txt` се запишани повеќе редови со броеви така што секој ред започнува со еден цел број (N>=1) што означува колку броеви следуваат по него во тој ред. 
Да се напише програма која на СИ за секој ред ќе го испечати бројот со најголема најзначајна цифра. 
Читањето на броеви завршува кога ќе се прочита 0.

.Решение `p_kol2_6.c`

[source,c]
----
include::{source_dir}/p_kol2_6.c[]
----

include::parts/footer.adoc[]

link:{sources_zip}/sp_kol2_src.zip[Source code ZIP]
